package com.example.shopeasy.Navigation


const val ROUTE_LOGIN="Login"
const val ROUTE_REGISTER="Register"
const val ROUTE_HOME="Home"
const val ROUTE_PROFILE="profile"
const val ROUTE_WEBVIEW="webview"
const val ROUTE_SEARCH="search"
const val ROUTE_STORES="stores"
const val ROUTE_TV="tv"
const val ROUTE_BOOKS="books"
const val ROUTE_AUDIO="audio"
const val ROUTE_COMPUTING="computing"
const val ROUTE_FOOD="food"
const val ROUTE_FASHION="fashion"
const val ROUTE_AUTOMOBILE="automobile"
const val ROUTE_GAMING="gaming"
const val ROUTE_GARDENING="gardening"
const val ROUTE_OFFICE="home&office"
const val ROUTE_KITCHEN="kitchen"
const val ROUTE_PHONES="phones"
const val ROUTE_SPORTING="sporting"
const val ROUTE_SUPERMARKET="supermarket"
const val ROUTE_HEALTH="health"